version: "3.8"

services:
  rul-api:
    build: .
    container_name: turbofan_prediction_service
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models # Syncs your local models folder with the container
    restart: always
